(** Types and functions for running unit tests. *)

type output = {
  log: string;                (** The logging produced while running the tests. *)
  results: Suite.result list; (** The results of running the test. *)
}
(** The output generated by running a test. *)

val run : Suite.t -> output
(** [run suite] runs [suite], and returns the logs and the test output. *)
