(** Types and functions for running unit tests. *)

type output = {
  log: string;                (** The logging produced while running the tests. *)
  results: Suite.result list; (** The results of running the test. *)
}
(** The output generated by running a test. *)

type summary = {
  log: string;                (** The logging produced while running the test,
                                  plus a summary of the results. *)
  passed: bool;               (** A flag indicating whether all the tests
                                  passed. *)
}
(** A summary of a test run, including all logs plus a flag indicating whether
    all the tests passed. *)

val run : Suite.t -> (output -> unit) -> unit
(** [run suite] runs [suite], passes the output to a supplied callback, and
    returns the result of the callback.. *)

val summarise : output -> summary
(** [summarise output] converts the output from running a suite into a summary
    of the results. *)
